In [1]:
import pandas as pd
import numpy as np

***GDP DATA***

In [2]:
#load gdp dataset, convert columns to county fip code
realgdp_ca = pd.read_csv('gdp-by-county-ca2.csv')
realgdp_ca.columns = [int(col.replace('REALGDPALL', '')) if col.startswith('REALGDPALL') else col for col in realgdp_ca.columns]

In [3]:
#load list of fip codes, replace fip codes in gdp dataset with county names
fips_df = pd.read_csv('https://raw.githubusercontent.com/kjhealy/fips-codes/master/state_and_county_fips_master.csv')
fips_ca = fips_df[fips_df['state'] == 'CA']
fips_county = dict(zip(fips_ca['fips'], fips_ca['name']))
realgdp_ca.rename(columns=fips_county, inplace=True)
#units (Thousands of Chained 2017 USD, Not Seasonally Adjusted)
realgdp_ca.attrs['units'] = 'Thousands of Chained 2017 USD'

In [4]:
realgdp_ca

,observation_date,Alameda County,Alpine County,Amador County,Butte County,Calaveras County,Colusa County,Contra Costa County,Del Norte County,El Dorado County,...,Sonoma County,Stanislaus County,Sutter County,Tehama County,Trinity County,Tulare County,Tuolumne County,Ventura County,Yolo County,Yuba County
0,2001-01-01,86924126,84720,1360828,6790163,1098393,908729,64845726,659710,5655039,...,22424276,16559172,2532153,1419839,327124,11635782,1914694,39016318,10021979,2204099
1,2002-01-01,87945920,87647,1572280,7281711,1193532,845631,64827092,667447,6145440,...,23360909,17211668,3067456,1518222,363755,10822959,2265038,40234620,10202456,2374643
2,2003-01-01,91564585,89449,1616440,7600395,1220905,989680,65646731,692526,6297920,...,23193391,17828749,3074716,1553812,386418,11393198,2296930,42820863,10568911,2502333
3,2004-01-01,92470454,86175,1685018,7713220,1201726,814567,68905840,728039,6564920,...,23112212,18906794,3111914,1628286,373886,12631250,2317515,46880813,11055339,2426950
4,2005-01-01,94611477,87711,1677506,7912397,1290494,853126,75014351,744646,6731682,...,23574318,19533906,3005880,1739505,352092,13871037,2433650,49219057,11230028,2461033
5,2006-01-01,97221046,88802,1669942,8195172,1246157,921396,75242782,773156,6937119,...,23737230,19987363,3235685,1657115,367853,13084688,2489599,54587334,11399368,2588931
6,2007-01-01,98832535,97501,1639393,8084613,1231004,1019449,73275314,791314,6825184,...,24262255,19706375,3384828,1688061,365651,14624649,2417989,59025486,12001509,2561887
7,2008-01-01,99236414,94188,1620129,7917794,1215672,1331160,90234175,858035,6820209,...,24112663,19117205,3719483,1580861,358199,13815747,2357542,54095039,12056502,2660591
8,2009-01-01,94214542,89805,1539261,8066507,1147589,1619244,78642291,807494,6575227,...,23049293,18863423,3905209,1563087,336077,12622564,2255875,53813657,11535085,2707581
9,2010-01-01,97503433,94445,1516280,8103725,1247463,1381681,70521397,806195,6588968,...,23744974,19014237,3613524,1666055,382431,13947483,2384417,53517947,11318089,2709494
10,2011-01-01,99901787,106013,1490526,8041960,1262941,1408579,61420189,802865,6730944,...,24211761,18963019,3310572,1624387,401963,14438491,2535427,50599745,11585911,2849855
11,2012-01-01,103075886,105258,1410001,7907486,1172114,1282490,61886376,768813,6523416,...,24729966,18692433,3158804,1626900,385015,13741919,2188505,49785812,11695460,2815429
12,2013-01-01,106957044,101992,1442873,8100816,1142856,1371562,63560918,758225,6626293,...,25403056,18926529,3270939,1680855,391092,14039836,2168522,50380642,12183328,2919556
13,2014-01-01,111256132,109676,1471869,7914931,1151410,1140452,68227043,758048,6886252,...,26431958,20164828,3108478,1767052,380181,15713728,2128541,50081745,12665705,2795079
14,2015-01-01,119277959,112863,1509231,8282989,1205964,1407340,69109358,770057,7138794,...,27693872,20967459,3282597,1774334,365641,15809561,2195073,50376211,13452602,2800154
15,2016-01-01,123298691,111940,1553868,8845128,1303589,1399430,68870149,793910,7690378,...,28392136,21301063,3265141,1827128,383405,16806339,2407029,50166157,14032538,3006985
16,2017-01-01,130430017,114872,1608472,9181452,1430443,1291669,71697154,767790,7932017,...,28853518,22191928,3235371,1932232,413913,17426838,2608796,50165884,14319346,3106720
17,2018-01-01,135481671,115488,1630629,9272932,1355160,1483162,75806177,786770,8234171,...,30213474,22810079,3488411,1927044,400158,17686115,2388479,50754467,14899646,3191495
18,2019-01-01,139438051,133602,1680454,9457300,1479943,1325940,78683211,777797,8352686,...,30482863,23329680,3476887,2017478,395798,18480075,2567544,51708632,15471476,3313354
19,2020-01-01,136360934,107899,1579109,8910788,1341160,1495139,71307929,783182,7822988,...,29572422,22651130,3574328,2026350,403924,18062395,2316248,51241052,14957942,3200163
20,2021-01-01,145802065,106967,1594467,9129906,1362842,1387578,77470793,811327,8191849,...,31655078,23715467,3866123,2075820,386888,18345174,2355456,53217781,15615946,3237690
21,2022-01-01,149679209,102957,1622769,9027053,1381565,1466671,77170082,815379,8345528,...,30954169,23803366,3948821,1992361,370035,18399182,2398321,53252680,15699176,3183292
22,2023-01-01,150532046,105610,1659330,9278380,1472506,1609218,78357593,844062,8833331,...,31011472,24067824,3915978,2135028,402737,18824792,2610180,53629861,15555485,3373337

Note: GDP is measured in Real Total GDP, meaning all the data is adjusted for inflation in 2017 dollars for a more accurate measure of economic growth

***MEDIAN INCOME DATA***

In [5]:
#load median income dataset, convert columns to county fip code
medianinc_ca = pd.read_csv('median-income-county-ca.csv')
medianinc_ca.columns = [col.replace('A052NCEN', '') if col.startswith('MHICA') else col for col in medianinc_ca.columns]
medianinc_ca.columns = [int(col.replace('MHICA', '')) if col.startswith('MHICA') else col for col in medianinc_ca.columns]
#replace fip codes in median income dataset with county names
medianinc_ca.rename(columns=fips_county, inplace=True)
#units (USD, Not Seasonally Adjusted)
medianinc_ca.attrs['units'] = 'USD, Unadjusted for inflation'

In [6]:
medianinc_ca

,observation_date,Alameda County,Alpine County,Amador County,Butte County,Calaveras County,Colusa County,Contra Costa County,Del Norte County,El Dorado County,...,Sonoma County,Stanislaus County,Sutter County,Tehama County,Trinity County,Tulare County,Tuolumne County,Ventura County,Yolo County,Yuba County
0,2001-01-01,54925,38401,41805,31342,40890,34722,64433,28841,51861,...,52873,39300,38013,30609,27464,31587,37745,56525,41851,29927
1,2002-01-01,55595,37691,43628,32124,42563,34556,65186,29028,53182,...,53230,40000,38585,31307,28170,32033,38770,57052,42412,30860
2,2003-01-01,56225,38825,44494,33528,43462,36579,64365,29990,54131,...,52088,41619,39718,32905,29063,33190,39620,57885,43612,32802
3,2004-01-01,57659,42827,47459,34891,46052,38350,65459,31502,56629,...,53645,43072,41289,34520,30307,34809,41067,59379,44810,34493
4,2005-01-01,60937,45283,52078,36303,47639,39186,69463,32724,62199,...,58110,46769,44914,33903,31434,38179,42381,66531,49378,35786
5,2006-01-01,64285,47515,50528,40023,52745,40240,74058,33765,67605,...,60656,48252,47174,35639,33070,41117,44991,71807,50027,37558
6,2007-01-01,68263,46136,54903,39466,51447,43882,76317,35910,64256,...,62279,50367,49104,36884,35439,40444,45478,72762,55988,40602
7,2008-01-01,70217,49320,53951,40308,52850,44622,78469,36729,67019,...,62314,50094,49146,38160,34726,44383,49151,76190,57877,46715
8,2009-01-01,68258,45391,54461,41196,51564,47472,75084,38252,68778,...,61985,48550,48073,38179,33546,39876,48027,71246,56120,40947
9,2010-01-01,66937,44241,49516,41168,50745,44981,73678,35438,65201,...,58703,47442,46188,38188,35207,42377,44751,71418,54433,41045
10,2011-01-01,67295,46706,51553,39208,50599,47469,74241,35598,61970,...,60792,44287,48749,37297,33163,40599,43530,74019,50174,43299
11,2012-01-01,70209,46336,51388,40748,50962,49871,74208,37305,68446,...,59855,46324,46524,38577,35162,40197,46624,71043,51040,41599
12,2013-01-01,72128,49392,52357,42395,52598,48897,78909,38663,63002,...,61020,47808,47903,43459,35708,39657,50774,76513,55011,41824
13,2014-01-01,76996,53003,54610,42302,53321,48006,80338,41419,70235,...,66949,50917,51827,40782,34961,42360,49476,74967,54509,41403
14,2015-01-01,81462,50882,55879,45369,52471,51118,83036,38963,75575,...,66463,51949,50810,40292,37669,42637,53136,79285,58766,46500
15,2016-01-01,89472,57481,59789,45097,57990,54861,90920,39458,75100,...,73496,54060,51283,40585,38727,45768,50431,79470,63645,46054
16,2017-01-01,95550,55755,60588,48634,58536,53595,95062,39996,78464,...,79511,58925,54102,41819,40676,46377,58776,82436,64900,53822
17,2018-01-01,101744,55384,58515,50945,62984,57249,101463,48518,81869,...,81002,59616,57879,47572,40680,48763,56500,84170,67804,47504
18,2019-01-01,107589,58112,62640,58394,68248,59048,106555,48979,86202,...,87084,62761,60910,51672,43881,56776,64729,91446,70951,56607
19,2020-01-01,113518,64542,68141,54718,66329,59422,106484,47442,87792,...,87366,64501,65791,61571,45113,62058,63336,90961,80668,56278
20,2021-01-01,108971,87570,68159,62982,68298,60725,110595,48108,87689,...,92999,73151,63246,53654,45508,57398,61396,95819,76247,60764
21,2022-01-01,121190,71646,74356,63353,73175,72963,119667,57297,104859,...,96312,75249,66071,58900,49485,64313,70108,101981,82359,63626
22,2023-01-01,119230,83265,80767,63084,77041,66675,122000,70231,107063,...,100157,81582,71968,58333,52079,71368,72329,106526,91192,71493

Note: Median Income is *not* adjusted for inflation

In [ ]:
#assign list of california counties
ca_counties = [
    "Alameda County",
    "Alpine County",
    "Amador County",
    "Butte County",
    "Calaveras County",
    "Colusa County",
    "Contra Costa County",
    "Del Norte County",
    "El Dorado County",
    "Fresno County",
    "Glenn County",
    "Humboldt County",
    "Imperial County",
    "Inyo County",
    "Kern County",
    "Kings County",
    "Lake County",
    "Lassen County",
    "Los Angeles County",
    "Madera County",
    "Marin County",
    "Mariposa County",
    "Mendocino County",
    "Merced County",
    "Modoc County",
    "Mono County",
    "Monterey County",
    "Napa County",
    "Nevada County",
    "Orange County",
    "Placer County",
    "Plumas County",
    "Riverside County",
    "Sacramento County",
    "San Benito County",
    "San Bernardino County",
    "San Diego County",
    "San Francisco County",
    "San Joaquin County",
    "San Luis Obispo County",
    "San Mateo County",
    "Santa Barbara County",
    "Santa Clara County",
    "Santa Cruz County",
    "Shasta County",
    "Sierra County",
    "Siskiyou County",
    "Solano County",
    "Sonoma County",
    "Stanislaus County",
    "Sutter County",
    "Tehama County",
    "Trinity County",
    "Tulare County",
    "Tuolumne County",
    "Ventura County",
    "Yolo County",
    "Yuba County"
]
ca_counties2 = [
    "Alameda",
    "Alpine",
    "Amador",
    "Butte",
    "Calaveras",
    "Colusa",
    "Contra Costa",
    "Del Norte",
    "El Dorado",
    "Fresno",
    "Glenn",
    "Humboldt",
    "Imperial",
    "Inyo",
    "Kern",
    "Kings",
    "Lake",
    "Lassen",
    "Los Angeles",
    "Madera",
    "Marin",
    "Mariposa",
    "Mendocino",
    "Merced",
    "Modoc",
    "Mono",
    "Monterey",
    "Napa",
    "Nevada",
    "Orange",
    "Placer",
    "Plumas",
    "Riverside",
    "Sacramento",
    "San Benito",
    "San Bernardino",
    "San Diego",
    "San Francisco",
    "San Joaquin",
    "San Luis Obispo",
    "San Mateo",
    "Santa Barbara",
    "Santa Clara",
    "Santa Cruz",
    "Shasta",
    "Sierra",
    "Siskiyou",
    "Solano",
    "Sonoma",
    "Stanislaus",
    "Sutter",
    "Tehama",
    "Trinity",
    "Tulare",
    "Tuolumne",
    "Ventura",
    "Yolo",
    "Yuba"
]

In [ ]:
#check to ensure every county is in the dataset
for county in ca_counties:
    assert county in realgdp_ca.columns
    assert county in medianinc_ca.columns

***PUBLIC SAFETY SPENDING DATA***

In [32]:
#
ca_expend = pd.read_csv('County_-_Expenditures_20250513.csv')
ca_expend = ca_expend[ca_expend['Entity Name'].isin(ca_counties2)]
ca_publicprot = ca_expend[ca_expend['Category'] == 'Public Protection']
justice_cat = ['Police Protection_Operating Expenditures', 'Detention and Correction', 'Judicial', 'Police Protection', 'Police Protection_Capital Outlay', 'Police Protection_Operating Expenditures']
ca_publicprot = ca_publicprot[ca_publicprot['Subcategory 1'].isin(justice_cat)]

In [ ]:
#get total spending for public protection by year
publicprottotal = ca_publicprot.groupby(['Entity Name', 'Fiscal Year'])['Values'].sum().reset_index()
publicprottotal.rename(columns={'Values': 'Total Spending'}, inplace=True)

     Entity Name  Fiscal Year  Total Spending
0        Alameda         2003       393405118
1        Alameda         2004       403815290
2        Alameda         2005       412566039
3        Alameda         2006       439809386
4        Alameda         2007       489083040
...          ...          ...             ...
1192        Yuba         2019        51346113
1193        Yuba         2020        55720542
1194        Yuba         2021        60285475
1195        Yuba         2022        63317701
1196        Yuba         2023        72229763

[1197 rows x 3 columns]

***

In [14]:
#some bullshit